# Generated by Django 2.0.2 on 2018-03-11 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gildencharakter',
            fields=[
                ('Charaktername', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Gildenrang', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Raiddatum', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Raidinformationen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spielerverwaltung.Raid')),
                ('Teilnehmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spielerverwaltung.Gildencharakter')),
            ],
        ),
        migrations.CreateModel(
            name='Spieler',
            fields=[
                ('Spielername', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Anlagedatum', models.DateField(auto_now_add=True)),
                ('Aktiv', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='raid',
            name='Raidteilnehmer',
            field=models.ManyToManyField(through='Spielerverwaltung.Raidinformationen', to='Spielerverwaltung.Gildencharakter'),
        ),
        migrations.AddField(
            model_name='gildencharakter',
            name='Spielername',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Spielerverwaltung.Spieler'),
        ),
    ]
