# Generated by Django 2.0.2 on 2018-03-11 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spielerverwaltung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gildencharakter',
            name='Spielername',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Spielerverwaltung.Spieler'),
        ),
    ]
