# Generated by Django 2.0.2 on 2018-03-24 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spielerverwaltung', '0003_auto_20180318_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidinformationen',
            name='Spieler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Spielerverwaltung.Spieler'),
        ),
        migrations.AddField(
            model_name='raidinformationen',
            name='did_participate',
            field=models.BooleanField(default=False),
        ),
    ]
