# Generated by Django 2.0.2 on 2018-03-24 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spielerverwaltung', '0004_auto_20180324_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raidinformationen',
            name='Spieler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Spielerverwaltung.Spieler'),
        ),
    ]
