# Generated by Django 2.0.2 on 2018-03-25 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spielerverwaltung', '0006_auto_20180324_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did_participate', models.BooleanField(default=False)),
                ('Raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spielerverwaltung.Raid')),
                ('Spieler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spielerverwaltung.Spieler')),
            ],
        ),
        migrations.RemoveField(
            model_name='raidinformationen',
            name='Spieler',
        ),
        migrations.RemoveField(
            model_name='raidinformationen',
            name='did_participate',
        ),
        migrations.AddField(
            model_name='raid',
            name='Teilnehmr',
            field=models.ManyToManyField(through='Spielerverwaltung.Attendency', to='Spielerverwaltung.Spieler'),
        ),
    ]
