# Generated by Django 2.0.2 on 2018-03-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spielerverwaltung', '0008_auto_20180325_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='WarcraftlogsID',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendency',
            unique_together={('Raid', 'Spieler')},
        ),
    ]
