# Generated by Django 2.0.2 on 2018-03-27 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spielerverwaltung', '0010_auto_20180327_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raid',
            options={'ordering': ['-Raiddatum']},
        ),
    ]
